main: net.natroutter.hubcore.HubCore
name: HubCore
version: ${project.version}
author: NATroutter
description: ${project.description}
api-version: 1.17
website: ${project.url}
softdepend:
  - PlaceholderAPI
  - Citizens
  - BetterParkour

